server:
  port: 9999

spring:
  datasource:
    username: root
    password: happybadminton
    url: jdbc:mysql:///happyb
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.hb: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1