server:
  port: 9999

spring:
  datasource:
    username: root
    password: happybadminton
    url: jdbc:mysql:///happyb
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.hb: debug